[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "krizovkar"
version = "0.1.0"
description = "Nástroj pro tvorbu švédských, klasických a dalších křížovek."
readme = "README.md"
requires-python = ">=3.14.1"
license = "CC0-1.0"
dependencies = [
    "jsonschema>=4.26,<5",
    "pyobjc-framework-Cocoa>=12.2.1,<13; sys_platform == 'darwin'",
    "pyphen>=0.17.2,<0.18",
    "ruamel.yaml>=0.19.1,<0.20",
]

[project.scripts]
krizovkar = "krizovkar.cli:main"
krizovkar-gui = "krizovkar.gui:main"

[project.urls]
Repository = "https://github.com/Glutexo/krizovkar"

[tool.hatch.build.targets.wheel]
packages = ["src/krizovkar"]
