"""Nástroje pro práci s křížovkami."""

from krizovkar.dictionary import (
    CrosswordDictionary,
    DictionaryEntry,
    DictionaryError,
    load_dictionary,
)
from krizovkar.generator import GenerationError, generate_swedish_grid

from krizovkar.model import (
    CellBar,
    Coordinate,
    CrosswordGrid,
    CrosswordSpecification,
    DEFAULT_SECRET_PART_LEGEND,
    DEFAULT_SECRET_LEGEND,
    EmptyCell,
    ExternalClue,
    Grid,
    GridCell,
    GridDimensions,
    HelpCell,
    LegendArrow,
    LegendCell,
    LetterCell,
    ModelError,
    SecretArrow,
    SecretCell,
    SecretCells,
    SecretDefinition,
    SecretPart,
    SecretParts,
    SecretWord,
    WordDirection,
    WordPlacement,
    load_crossword_grid,
    load_crossword_specification,
    secret_path_arrows,
    write_crossword_grid,
)
from krizovkar.renderer import RenderError, render_pdf
from krizovkar.validation import (
    ValidationIssue,
    ValidationReport,
    check_crossword_grid,
    check_dense_swedish_grid,
    validate_crossword_grid_file,
    validate_dense_swedish_grid_file,
)

__all__ = [
    "CellBar",
    "Coordinate",
    "CrosswordDictionary",
    "CrosswordGrid",
    "CrosswordSpecification",
    "DEFAULT_SECRET_PART_LEGEND",
    "DEFAULT_SECRET_LEGEND",
    "DictionaryEntry",
    "DictionaryError",
    "EmptyCell",
    "ExternalClue",
    "Grid",
    "GridCell",
    "GridDimensions",
    "GenerationError",
    "HelpCell",
    "LegendArrow",
    "LegendCell",
    "LetterCell",
    "ModelError",
    "RenderError",
    "SecretArrow",
    "SecretCell",
    "SecretCells",
    "SecretDefinition",
    "SecretPart",
    "SecretParts",
    "SecretWord",
    "ValidationIssue",
    "ValidationReport",
    "WordDirection",
    "WordPlacement",
    "check_crossword_grid",
    "check_dense_swedish_grid",
    "generate_swedish_grid",
    "load_dictionary",
    "load_crossword_grid",
    "load_crossword_specification",
    "render_pdf",
    "secret_path_arrows",
    "validate_crossword_grid_file",
    "validate_dense_swedish_grid_file",
    "write_crossword_grid",
]
